"""add_base_salary_and_payroll_updates

Revision ID: 59c1e9944901
Revises: 864c0b53fb31
Create Date: 2026-01-03 15:50:46.400997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59c1e9944901'
down_revision: Union[str, Sequence[str], None] = '864c0b53fb31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payrolls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('pay_period_start', sa.Date(), nullable=False),
    sa.Column('pay_period_end', sa.Date(), nullable=False),
    sa.Column('basic_salary', sa.Float(), nullable=False),
    sa.Column('deductions', sa.Float(), nullable=False),
    sa.Column('net_pay', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payrolls_id'), 'payrolls', ['id'], unique=False)
    op.drop_index(op.f('idx_salary_employee'), table_name='salary_slips')
    op.drop_table('salary_slips')
    op.drop_table('salary_structures')
    op.drop_index(op.f('idx_attendance_employee_date'), table_name='attendance_records')
    op.add_column('employees', sa.Column('base_salary', sa.Float(), nullable=False, server_default='0'))
    op.alter_column('employees', 'job_title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('employees', 'department',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint(op.f('employees_user_id_key'), 'employees', type_='unique')
    op.create_index(op.f('ix_employees_user_id'), 'employees', ['user_id'], unique=True)
    op.drop_constraint(op.f('employees_user_id_fkey'), 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('idx_leave_employee_status'), table_name='leave_requests')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_leave_employee_status'), 'leave_requests', ['employee_id', 'status'], unique=False)
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key(op.f('employees_user_id_fkey'), 'employees', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_employees_user_id'), table_name='employees')
    op.create_unique_constraint(op.f('employees_user_id_key'), 'employees', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('employees', 'department',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('employees', 'job_title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('employees', 'base_salary')
    op.create_index(op.f('idx_attendance_employee_date'), 'attendance_records', ['employee_id', 'work_date'], unique=False)
    op.create_table('salary_structures',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('base_salary', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('allowances', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('deductions', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('effective_from', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('salary_structures_employee_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('salary_structures_pkey')),
    sa.UniqueConstraint('employee_id', 'effective_from', name=op.f('uq_salary_structures_employee_effective_from'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('salary_slips',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('month', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('gross_salary', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('net_salary', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('salary_slips_employee_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('salary_slips_pkey')),
    sa.UniqueConstraint('employee_id', 'month', name=op.f('uq_salary_slips_employee_month'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_salary_employee'), 'salary_slips', ['employee_id'], unique=False)
    op.drop_index(op.f('ix_payrolls_id'), table_name='payrolls')
    op.drop_table('payrolls')
    # ### end Alembic commands ###
